### ISSUE TITLE
C/C++ Additional Directory Issue

### ISSUE THREAD

**Issue by IceMan0224** [mateeeeeee/Adria-DX11#3]
ThirdParty\tinygltf
Thirdparty\tinyobjloader
Thirdparty\FastNoiseLite

Path is wrong just do compiled

Please change 
$(SolutionDir)ThirdParty\tinygltf 
$(SolutionDir)Thirdparty\tinyobjloader
$(SolutionDir)Thirdparty\FastNoiseLite
 then all good Path

**Comment by mateeeeeee** [comment]
Thanks, fixed in the latest commit.
