### ISSUE TITLE
Dx12 Ultimate emu?

### ISSUE THREAD

**Issue by JimmisAtha** [mateeeeeee/Adria-DX11#7]
Direct X 12 Ultimate is only supported in RTX,  so can we make a game think that the PC supports it?

**Comment by mateeeeeee** [comment]
Sorry, but I don't understand your question

**Comment by JimmisAtha** [comment]
I would like a software that makes my PC think that DX12 Ultimate is supported!  ....

**Comment by mateeeeeee** [comment]
This is DirectX 11 project. Did you maybe mean to open this issue here https://github.com/mateeeeeee/Adria-DX12?
If so, Adria-DX12 should work on non-RTX cards, it works on my integrated Intel card (it doesn't support DX12 ultimate features but has supported fallback in those cases)
